#!/bin/bash

# Helper script for running CTS tests with all the right params.
# Example usage:
#  run-test <module> <package_name>  // To run all the tests in a package.
#  run-test <module> <package_name>.<class_name>  // To run all the tests in a class.
#  run-test <module> <package_name>.<class_name>#<method_name>  // To run a specific test in a class.

echo " "
echo "Running module $1 test...$2"
echo " "
cts-tradefed run commandAndExit cts-dev --module $1 --test $2 --disable-reboot --skip-device-info --skip-all-system-status-check --skip-preconditions
