# This file is autogenerated by hidl-gen. Do not edit manually.

LOCAL_PATH := $(call my-dir)

################################################################################

include $(CLEAR_VARS)
LOCAL_MODULE := android.frameworks.displayservice-V1.0-java
LOCAL_MODULE_CLASS := JAVA_LIBRARIES

intermediates := $(call local-generated-sources-dir, COMMON)

HIDL := $(HOST_OUT_EXECUTABLES)/hidl-gen$(HOST_EXECUTABLE_SUFFIX)

LOCAL_JAVA_LIBRARIES := \
    android.hidl.base-V1.0-java \


#
# Build types.hal (Status)
#
GEN := $(intermediates)/android/frameworks/displayservice/V1_0/Status.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.frameworks:frameworks/hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        android.frameworks.displayservice@1.0::types.Status

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build IDisplayEventReceiver.hal
#
GEN := $(intermediates)/android/frameworks/displayservice/V1_0/IDisplayEventReceiver.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/IDisplayEventReceiver.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/IEventCallback.hal
$(GEN): $(LOCAL_PATH)/IEventCallback.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/types.hal
$(GEN): $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.frameworks:frameworks/hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        android.frameworks.displayservice@1.0::IDisplayEventReceiver

$(GEN): $(LOCAL_PATH)/IDisplayEventReceiver.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build IDisplayService.hal
#
GEN := $(intermediates)/android/frameworks/displayservice/V1_0/IDisplayService.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/IDisplayService.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/IDisplayEventReceiver.hal
$(GEN): $(LOCAL_PATH)/IDisplayEventReceiver.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.frameworks:frameworks/hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        android.frameworks.displayservice@1.0::IDisplayService

$(GEN): $(LOCAL_PATH)/IDisplayService.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build IEventCallback.hal
#
GEN := $(intermediates)/android/frameworks/displayservice/V1_0/IEventCallback.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/IEventCallback.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.frameworks:frameworks/hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        android.frameworks.displayservice@1.0::IEventCallback

$(GEN): $(LOCAL_PATH)/IEventCallback.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)
include $(BUILD_JAVA_LIBRARY)


################################################################################

include $(CLEAR_VARS)
LOCAL_MODULE := android.frameworks.displayservice-V1.0-java-static
LOCAL_MODULE_CLASS := JAVA_LIBRARIES

intermediates := $(call local-generated-sources-dir, COMMON)

HIDL := $(HOST_OUT_EXECUTABLES)/hidl-gen$(HOST_EXECUTABLE_SUFFIX)

LOCAL_STATIC_JAVA_LIBRARIES := \
    android.hidl.base-V1.0-java-static \


#
# Build types.hal (Status)
#
GEN := $(intermediates)/android/frameworks/displayservice/V1_0/Status.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.frameworks:frameworks/hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        android.frameworks.displayservice@1.0::types.Status

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build IDisplayEventReceiver.hal
#
GEN := $(intermediates)/android/frameworks/displayservice/V1_0/IDisplayEventReceiver.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/IDisplayEventReceiver.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/IEventCallback.hal
$(GEN): $(LOCAL_PATH)/IEventCallback.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/types.hal
$(GEN): $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.frameworks:frameworks/hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        android.frameworks.displayservice@1.0::IDisplayEventReceiver

$(GEN): $(LOCAL_PATH)/IDisplayEventReceiver.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build IDisplayService.hal
#
GEN := $(intermediates)/android/frameworks/displayservice/V1_0/IDisplayService.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/IDisplayService.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/IDisplayEventReceiver.hal
$(GEN): $(LOCAL_PATH)/IDisplayEventReceiver.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.frameworks:frameworks/hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        android.frameworks.displayservice@1.0::IDisplayService

$(GEN): $(LOCAL_PATH)/IDisplayService.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build IEventCallback.hal
#
GEN := $(intermediates)/android/frameworks/displayservice/V1_0/IEventCallback.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/IEventCallback.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.frameworks:frameworks/hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        android.frameworks.displayservice@1.0::IEventCallback

$(GEN): $(LOCAL_PATH)/IEventCallback.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)
include $(BUILD_STATIC_JAVA_LIBRARY)



include $(call all-makefiles-under,$(LOCAL_PATH))
