#!/bin/bash

verbose_run() {
  echo "$@"
  $@
}

sim_PATH=/mtktools/Utility/Skyfish/IA-EXE
ia_sim=$sim_PATH/modelia-sim-latest

if [ ! -f $ia_sim ]; then
  echo "Error: no modelia-sim-latest in $ia_sim"
  exit 1
fi

verbose_run "$ia_sim --cpu $ia_PROC --elf $@"
